version: '3'
services:
  backend:
    build:
      context: fr-administration
    ports:
      - ${BACK_PORT}:3000
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=5432
    depends_on:
      - db
  db:
    image: postgres:15.1
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
    volumes:
      - ./db:/var/lib/postgresql/data

  web:
    image: nginx:1.23.2
    volumes:
    - ./fr-administration-front:/usr/share/nginx/html
    ports:
    - "${FRONT_PORT}:80"
    environment:
    - NGINX_HOST=localhost
    - NGINX_PORT=80