services:

  mail:
    build:
      context: mail
      target: prod
    image: fgdou/wm-project-mail
    depends_on:
      - mom
    environment:
      - EMAIL_FROM=fabigoardou@gmail.com
      - EMAIL_HOST=smtp
      - EMAIL_PORT=1025
      - RABBIT_HOST=${RABBIT_HOST}
      - RABBIT_PORT=${RABBIT_PORT}
      - RABBIT_USER=${RABBIT_USER}
      - RABBIT_PWD=${RABBIT_PWD}
      - RABBIT_QUEUE=${RABBIT_QUEUE}

  front:
    build:
      context: ./fr-administration-front
      target: prod
    image: fgdou/wm-project-front

  proxy:
    build:
      context: nginx
      target: prod
    ports:
      - ${FRONT_PORT}:80
    depends_on:
      - front
      - back
      - mom
      - smtp
      - grafana
      - prometheus
    image: fgdou/wm-project-proxy


  back:
    build:
      context: ./fr-administration
      target: prod
    depends_on:
      - db
      - mom
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=5432
      - RABBIT_HOST=${RABBIT_HOST}
      - RABBIT_PORT=${RABBIT_PORT}
      - RABBIT_USER=${RABBIT_USER}
      - RABBIT_PWD=${RABBIT_PWD}
      - RABBIT_QUEUE=${RABBIT_QUEUE}
    image: fgdou/wm-project-back
  
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
    volumes:
      - ./db:/var/lib/postgresql/data

  mom:
    hostname: mom
    image: fgdou/wm-project-mom
    build:
      context: rabbitmq
      target: prod
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PWD}
      - RABBITMQ_NODE_PORT=${RABBIT_PORT}

  smtp:
    image: maildev/maildev:2.0.5

  grafana:
    image: fgdou/wm-project-grafana
    build:
      context: grafana
      target: prod
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PWD}

  prometheus:
    build:
      context: prometheus
      target: prod
    image: fgdou/wm-project-prometheus
    depends_on:
      - mom
      - back
      - mail
      - k6export
  
  k6:
    build:
      context: k6
      target: prod
    image: fgdou/wm-project-k6
    environment:
      - API_URL=http://back:${BACK_PORT}
      - K6_PROMETHEUS_RW_SERVER_URL=prometheus:9090
      - K6_STATSD_ADDR=k6export:9125
      - TEST_NAME=stress_test # smoke_test, load_test, soak_test, stress_test
    depends_on:
      - back
      - k6export

  k6export:
    build:
      context: k6export
      target: prod
    image: fgdou/wm-project-k6export
