services:

  mail:
    build:
      context: mail
      target: prod
    image: fgdou/wm-project-mail
    depends_on:
      - mom

  front:
    build:
      context: ./fr-administration-front
      target: prod
    image: fgdou/wm-project-front

  proxy:
    build:
      context: nginx
      target: prod
    ports:
      - ${FRONT_PORT}:80
    depends_on:
      - front
      - back
    image: fgdou/wm-project-proxy


  back:
    build:
      context: ./fr-administration
      target: prod
    depends_on:
      - db
      - mom
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=5432
    image: fgdou/wm-project-back
  
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
    volumes:
      - ./db:/var/lib/postgresql/data

  mom:
    hostname: mom
    image: rabbitmq:3.11.5-management
    volumes:
      - ./rabbitmq/conf:/etc/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PWD}

  smtp:
    image: maildev/maildev:2.0.5

  grafana:
    image: grafana/grafana:9.3.2
    environment:
      - UID=${UID}
      - GID=${GID}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PWD}
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana/dashboards/:/var/lib/grafana/dashboards
      - ./grafana/config.ini:/etc/grafana/grafana.ini
    user: "${UID}:${GID}"

  prometheus:
    image: bitnami/prometheus:2.41.0
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.external-url=/prometheus/
      - --web.route-prefix=/
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    user: "${UID}:${GID}"
    environment:
      - UID=${UID}
      - GID=${GID}
    depends_on:
      - mom
      - back
      - mail
      - k6export
  
  k6:
    image: ./k6
    ports:
      - "${K6_PORT}:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:${INFLUX_DB_PORT}/k6
      - API_URL=http://back:${BACK_PORT}
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090
      - K6_STATSD_ENABLE_TAGS=true
      - K6_STATSD_ADDR=k6export:9125
      - TEST_NAME=stress_test # smoke_test, load_test, soak_test, stress_test
    volumes:
      - ./k6:/scripts
    command: run -o statsd /scripts/main.js --verbose
    depends_on:
      - back

  k6export:
    image: ./k6export
    ports:
      - ${K6_EXPORT_PORT}:9102
      - ${K6_SEND_PORT}:9125 
      - ${K6_SEND_PORT}:9125/udp
    volumes:
      - ./k6export/statsd_mapping.yml:/tmp/statsd_mapping.yml
    command:
      - --statsd.mapping-config=/tmp/statsd_mapping.yml
    depends_on:
      - k6