version: '3'
services:
  mail:
    build:
      context: mail
      target: dev

  backend:
    build: fr-administration
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=5432
    depends_on:
      - db
    volumes:
      - ./fr-administration:/app
  db:
    image: postgres:15.1
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
    volumes:
      - ./db:/var/lib/postgresql/data

  frontend:
    build: fr-administration-front
    environment:
      - BACK_URL=${BACK_URL}
      - FRONT_URL=${FRONT_URL}
    volumes:
      - ./fr-administration-front:/app
    depends_on:
      - backend


  proxy:
    build:
      context: nginx
    ports:
    - "${FRONT_PORT}:80"
    environment:
    - NGINX_HOST=${HOST}
    - NGINX_PORT=80
    depends_on:
      - backend
      - frontend

  mom:
    hostname: mom
    image: rabbitmq:3-management
    volumes:
      - ./rabbitmq/core:/var/lib/rabbitmq/
      - ./rabbitmq/conf:/etc/rabbitmq/
    ports:
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PWD}
