services:

  mail:
    build:
      context: mail
      target: prod
    image: fgdou/wm-project-mail
    depends_on:
      - mom

  front:
    build:
      context: ./fr-administration-front
      target: prod
    image: fgdou/wm-project-front

  proxy:
    build:
      context: nginx
      target: prod
    ports:
      - ${FRONT_PORT}:80
    depends_on:
      - front
      - back
    image: fgdou/wm-project-proxy


  back:
    build:
      context: ./fr-administration
      target: prod
    depends_on:
      - db
      - mom
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=5432
    image: fgdou/wm-project-back
  
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
    volumes:
      - ./db:/var/lib/postgresql/data

  mom:
    hostname: mom
    image: fgdou/wm-project-mom
    build:
      context: rabbitmq
      target: prod
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PWD}

  smtp:
    image: maildev/maildev:2.0.5

  grafana:
    image: grafana/grafana:9.3.2
    environment:
      - UID=${UID}
      - GID=${GID}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PWD}
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana/dashboards/:/var/lib/grafana/dashboards
      - ./grafana/config.ini:/etc/grafana/grafana.ini
    user: "${UID}:${GID}"

  prometheus:
    image: bitnami/prometheus:2.41.0
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.external-url=/prometheus/
      - --web.route-prefix=/
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/data:/opt/bitnami/prometheus/data
    user: "${UID}:${GID}"
    environment:
      - UID=${UID}
      - GID=${GID}
    depends_on:
      - mom
      - back
      - mail