services:
  front:
    build: ./fr-administration-front
    ports:
      - '8080:80'
    depends_on:
      - back
  back:
    build: ./fr-administration
    depends_on:
      - db
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example