services:

  mail:
    image: fgdou/wm-project-mail
    depends_on:
      - mom
    restart: always

  front:
    image: fgdou/wm-project-front
    restart: always

  proxy:
    ports:
      - 80:80
    depends_on:
      - front
      - back
    image: fgdou/wm-project-proxy
    restart: always

  back:
    depends_on:
      - db
      - mom
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=esir
      - DB_DATABASE=WMproject
      - DB_PORT=5432
    image: fgdou/wm-project-back
    restart: always
  
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=esir
      - POSTGRES_DB=WMproject
      - POSTGRES_USER=user
    volumes:
      - ./db:/var/lib/postgresql/data

  mom:
    hostname: mom
    image: fgdou/wm-project-mom
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    restart: always

  smtp:
    image: maildev/maildev:2.0.5
    restart: always

  grafana:
    image: grafana/grafana:9.3.2
    environment:
      - UID=${UID}
      - GID=${GID}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PWD}
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana/dashboards/:/var/lib/grafana/dashboards
      - ./grafana/config.ini:/etc/grafana/grafana.ini
    user: "${UID}:${GID}"

  prometheus:
    image: bitnami/prometheus:2.41.0
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.external-url=/prometheus/
      - --web.route-prefix=/
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/data:/opt/bitnami/prometheus/data
    user: "${UID}:${GID}"
    environment:
      - UID=${UID}
      - GID=${GID}
    depends_on:
      - mom
      - back
      - mail