services:
  front:
    build: ./fr-administration-front
    ports:
      - '8080:80'
    depends_on:
      - back
  back:
    build: ./fr-administration
    links:
      - db
  
  db:
    image: postgres
    restart: always
    # ports:
    #   - '5432:5432'
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports: 
      - 8081:8080