services:
  front_build:
    image: node
    volumes:
      - ./fr-administration-front:/app
    working_dir: /app
    command: yarn watch
  front_host:
    image: nginx
    ports:
      - '8080:80'
    depends_on:
      - back
      - front_build
    volumes:
      - ./fr-administration-front/dist/fr-administration-front:/usr/share/nginx/html
      - ./fr-administration-front/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  back:
    image: node
    depends_on:
      - db
    ports:
      - '8082:3000'
    volumes:
      - ./fr-administration:/app
    working_dir: /app
    command: yarn start:dev
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=example
      - DB_DATABASE=postgres
      - DB_PORT=5432
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  # connect to adminer : http://localhost:8081/?pgsql=db&username=postgres&db=postgres&ns=public
  # server :             db
  # user :               postgres
  # password :           example
  # database :           postgres


  # Front : http://localhost:8080
  # Adminer : http://localhost:8081
  # Back : http://localhost:8082
