services:

  mail:
    build:
      context: mail
      target: dev
    depends_on:
      - mom

  front:
    build:
      context: ./fr-administration-front
      target: dev
    volumes:
      - ./fr-administration-front/src:/app/src:ro

  proxy:
    build:
      context: nginx
      target: dev
    ports:
      - ${FRONT_PORT}:80
    depends_on:
      - front
      - back
      - mom
      - adminer
      - smtp
      - grafana
      - prometheus


  back:
    build:
      context: ./fr-administration
      target: dev
    depends_on:
      - db
      - mom
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=5432
    volumes:
      - ./fr-administration/src:/app/src:ro

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
    volumes:
      - ./db:/var/lib/postgresql/data

  mom:
    hostname: mom
    image: rabbitmq:3.11.5-management
    volumes:
      - ./rabbitmq/conf:/etc/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PWD}

  adminer:
    image: adminer

  smtp:
    image: maildev/maildev:2.0.5

  grafana:
    image: grafana/grafana:9.3.2
    environment:
      - UID=${UID}
      - GID=${GID}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PWD}
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana/dashboards/:/var/lib/grafana/dashboards
      - ./grafana/config.ini:/etc/grafana/grafana.ini
    user: "${UID}:${GID}"

  prometheus:
    image: bitnami/prometheus:2.41.0
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.external-url=/prometheus/
      - --web.route-prefix=/
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    user: "${UID}:${GID}"
    environment:
      - UID=${UID}
      - GID=${GID}
    depends_on:
      - mom
      - back
      - mail
      - k6export
  
  k6:
    image: grafana/k6:0.42.0
    environment:
      - API_URL=http://back:${BACK_PORT}
      - K6_PROMETHEUS_RW_SERVER_URL=prometheus:9090
      - K6_STATSD_ENABLE_TAGS=true
      - K6_STATSD_ADDR=k6export:9125
      - TEST_NAME=${K6_TEST_TYPE}
    volumes:
      - ./k6:/scripts
    command: run -o statsd /scripts/main.js --verbose
    depends_on:
      - back
      - k6export

  k6export:
    image: prom/statsd-exporter
    volumes:
      - ./k6export/statsd_mapping.yml:/tmp/statsd_mapping.yml
    command:
      - --statsd.mapping-config=/tmp/statsd_mapping.yml
